
oswizard_forum_welcome:
    path: /
    defaults: { _controller: oswizardForumBundle:Forum:index }
    
oswizard_forum_show_section:
    path: /section/{idSection}
    defaults: { _controller: oswizardForumBundle:Forum:showSection }
    requirements:
        idSection: \d+
        
oswizard_forum_show_post:
    path: /section/post/{idPost}
    defaults: { _controller: oswizardForumBundle:Forum:showPost }
    requirements:
        idPost: \d+
        
oswizard_forum_add_section:
    path: /section
    defaults: { _controller: oswizardForumBundle:Forum:addSection }
    
oswizard_forum_add_post:
    path: /section/post/{idSection}
    defaults: { _controller: oswizardForumBundle:Forum:addPost }
    requirements:
        idSection: \d+